# Generated by Django 4.2.7 on 2025-07-27 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageClassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('predicted_class', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('all_predictions', models.JSONField()),
                ('recommendations', models.JSONField()),
                ('is_preprocessed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
