# Generated by Django 4.2.23 on 2025-07-28 16:47

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato_classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageclassification',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='potato_disease_classification/'),
        ),
    ]
