# Generated by Django 4.2.23 on 2025-07-28 17:48

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato_classifier', '0002_alter_imageclassification_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageclassification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Image Classification', 'verbose_name_plural': 'Image Classifications'},
        ),
        migrations.AddField(
            model_name='imageclassification',
            name='image_size',
            field=models.CharField(blank=True, help_text='Original image dimensions', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='imageclassification',
            name='processing_time',
            field=models.FloatField(blank=True, help_text='Processing time in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='imageclassification',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
